# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

omp_thread_count <- function() {
    .Call('FTRL_omp_thread_count', PACKAGE = 'FTRL')
}

create_ftrl_model <- function(z_inp, n_inp, alpha, beta, lambda1, lambda2, dropout, n_features) {
    .Call('FTRL_create_ftrl_model', PACKAGE = 'FTRL', z_inp, n_inp, alpha, beta, lambda1, lambda2, dropout, n_features)
}

get_ftrl_weights <- function(ptr) {
    .Call('FTRL_get_ftrl_weights', PACKAGE = 'FTRL', ptr)
}

ftrl_partial_fit <- function(m, y, ptr, do_update = 1L, nthread = 0L) {
    .Call('FTRL_ftrl_partial_fit', PACKAGE = 'FTRL', m, y, ptr, do_update, nthread)
}

